import type { CropType } from './types';

interface CropConfig {
  id: CropType;
  image: string;
  pest: string;
  yields: {
    veryHigh: string;
    high: string;
    moderate: string;
    low: string;
    veryLow: string;
  };
  baseYield: number;
  soilSensitivity: number;
  nutritionSensitivity: number;
  weatherSensitivity: {
    drought: string;
    cold: string;
    flood: string;
  };
  seedPrice: {
    conventional: number;
    organic: number;
  };
  marketValue: {
    conventional: number;
    organic: number;
  };
  special?: string;
}

export const APP_DOMAIN = 'https://soil.app';

export const GAME_CONSTANTS = {
  SOIL: {
    START: 80,
    FALLOW_RECOVERY: 0.3,
    CROP_ROTATION_BONUS: 0.02,
    CROP_ROTATION_PENALTY: -0.02,
    FERTILIZER_SYNTHETIC_IMPACT: -0.04,
    PESTICIDE_IMPACT: -0.02,
    MACHINE_IMPACT: [0, -0.002, -0.01, -0.05, -0.1],
    ORGANISMS_SOIL_BONUS: 0.005,
    MONOCULTURE_PENALTY: -0.06,
    NUTRITION_OVER_PENALTY_START: 110,
    NUTRITION_OVER_PENALTY_FACTOR: -0.002,
    SYNTHETIC_BURN_THRESHOLD: 100,
    SYNTHETIC_BURN_PENALTY: -0.05,
    PLANTATION_GAINS: {
      Fieldbean: 0.05,
      Pea: 0.04,
      Oat: 0.015,
      Rye: 0.015,
      Beet: 0.01,
      Grass: 0.06,
    } as Record<string, number>,
    PLANTATION_LOSSES: {
      Barley: -0.005,
      Potato: -0.01,
      Corn: -0.01,
      Wheat: -0.005,
      Beet: -0.005,
      Rapeseed: -0.005,
    } as Record<string, number>,
  },
  NUTRITION: {
    START: 80,
    MAX: 150,
    BASE_DECLINE: 0.12,
    FERTILIZER_SYNTHETIC: 40,
    FERTILIZER_ORGANIC: 35,
    FIELDBEAN_BONUS: 20,
    ANIMALS_REQUIRED_RATIO: 0.2,
  },
  MACHINE_FACTORS: {
    YIELD_BONUS: [0, 0.12, 0.3, 0.55, 0.85],
    LABOR_COST_REDUCTION: [1, 0.75, 0.5, 0.3, 0.1],
    BASE_LABOR_COST: 1500,
    INVESTMENT_COST: [0, 400, 1500, 4000, 10000],
  },
  WEATHER_EFFECTS: {
    Normal: { yield: 1.0, soil: 0 },
    Drought: { yield: 0.7, soil: -0.01 },
    LateFrost: { yield: 0.8, soil: 0 },
    SummerDrought: { yield: 0.6, soil: -0.02 },
    Flood: { yield: 0.6, soil: -0.02 },
    Storm: { yield: 0.8, soil: -0.01 },
  } as Record<string, { yield: number; soil: number }>,
  VERMIN_EFFECTS: {
    None: { yield: 1.0, organic_multiplier: 1.0 },
    Pests: { yield: 0.7, organic_multiplier: 1.2 },
  } as Record<string, { yield: number; organic_multiplier: number }>,
  CROPS: {
    Fieldbean: {
      id: 'Fieldbean',
      name: $localize`:@@crop.fieldbean:Ackerbohne`,
      description: $localize`:@@crop.fieldbean.desc:Ackerbohne`,
      image: 'ackerbohne.webp',
      pest: 'Blattlaus',
      yields: { veryHigh: '≥ 48', high: '36-47', moderate: '24-35', low: '13-23', veryLow: '< 13' },
      baseYield: 60,
      soilSensitivity: 1.2,
      nutritionSensitivity: 0.5,
      weatherSensitivity: { drought: 'Stark', cold: 'Mäßig', flood: 'Stark' },
      seedPrice: { conventional: 150, organic: 180 },
      marketValue: { conventional: 22, organic: 40 },
      special: 'Ackerbohnen erhöhen den Mineralstoffgehalt und die Bodenqualität.',
    },
    Barley: {
      id: 'Barley',
      name: $localize`:@@crop.barley:Gerste`,
      description: $localize`:@@crop.barley.desc:Gerste`,
      image: 'gerste.webp',
      baseYield: 95,
      soilSensitivity: 1.5,
      nutritionSensitivity: 0.8,
      pest: 'Blattlaus',
      yields: { veryHigh: '≥ 64', high: '48-63', moderate: '32-47', low: '17-31', veryLow: '< 17' },
      weatherSensitivity: { drought: 'Mäßig', cold: 'Mäßig', flood: 'Mäßig' },
      seedPrice: { conventional: 90, organic: 110 },
      marketValue: { conventional: 20, organic: 35 },
      special: 'Gerste ist robust und vielseitig.',
    },
    Oat: {
      id: 'Oat',
      name: $localize`:@@crop.oat:Hafer`,
      description: $localize`:@@crop.oat.desc:Hafer`,
      image: 'hafer.webp',
      pest: 'Fritfliege',
      yields: { veryHigh: '≥ 56', high: '42-55', moderate: '28-41', low: '15-27', veryLow: '< 15' },
      baseYield: 70,
      soilSensitivity: 1.4,
      nutritionSensitivity: 0.7,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 80, organic: 100 },
      marketValue: { conventional: 20, organic: 38 },
      special: 'Hafer verbessert die Bodenqualität.',
    },
    Potato: {
      id: 'Potato',
      name: $localize`:@@crop.potato:Kartoffel`,
      description: $localize`:@@crop.potato.desc:Kartoffel`,
      image: 'kartoffel.webp',
      pest: 'Kartoffelkäfer',
      yields: { veryHigh: '≥ 296', high: '222-295', moderate: '148-221', low: '75-147', veryLow: '< 75' },
      baseYield: 370,
      soilSensitivity: 2.0,
      nutritionSensitivity: 1.2,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 800, organic: 1000 },
      marketValue: { conventional: 12, organic: 25 },
    },
    Corn: {
      id: 'Corn',
      name: $localize`:@@crop.corn:Mais`,
      description: $localize`:@@crop.corn.desc:Mais`,
      image: 'mais.webp',
      pest: 'Maiszünsler',
      yields: { veryHigh: '≥ 88', high: '66-87', moderate: '44-65', low: '23-43', veryLow: '< 23' },
      baseYield: 110,
      soilSensitivity: 1.8,
      nutritionSensitivity: 1.0,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 100, organic: 120 },
      marketValue: { conventional: 25, organic: 40 },
    },
    Rye: {
      id: 'Rye',
      name: $localize`:@@crop.rye:Roggen`,
      description: $localize`:@@crop.rye.desc:Roggen`,
      image: 'roggen.webp',
      pest: 'Blattlaus',
      yields: { veryHigh: '≥ 80', high: '60-79', moderate: '40-59', low: '20-39', veryLow: '< 20' },
      baseYield: 100,
      soilSensitivity: 1.2,
      nutritionSensitivity: 0.7,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Mäßig', flood: 'Stark' },
      seedPrice: { conventional: 90, organic: 110 },
      marketValue: { conventional: 18, organic: 35 },
      special: 'Roggen verbessert die Bodenqualität.',
    },
    Wheat: {
      id: 'Wheat',
      name: $localize`:@@crop.wheat:Weizen`,
      description: $localize`:@@crop.wheat.desc:Weizen`,
      image: 'weizen.webp',
      pest: 'Blattlaus',
      yields: { veryHigh: '≥ 92', high: '69-91', moderate: '46-68', low: '24-45', veryLow: '< 24' },
      baseYield: 115,
      soilSensitivity: 1.8,
      nutritionSensitivity: 1.1,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 100, organic: 120 },
      marketValue: { conventional: 25, organic: 45 },
    },
    Beet: {
      id: 'Beet',
      name: $localize`:@@crop.beet:Zuckerrübe`,
      description: $localize`:@@crop.beet.desc:Zuckerrübe`,
      image: 'zuckerruebe.webp',
      pest: 'Drahtwurm',
      yields: { veryHigh: '≥ 456', high: '342-455', moderate: '228-341', low: '115-227', veryLow: '< 115' },
      baseYield: 570,
      soilSensitivity: 1.6,
      nutritionSensitivity: 1.1,
      weatherSensitivity: { drought: 'Stark', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 150, organic: 180 },
      marketValue: { conventional: 3.5, organic: 6 },
      special: 'Zuckerrüben verbessern die Bodenqualität.',
    },
    Rapeseed: {
      id: 'Rapeseed',
      name: $localize`:@@crop.rapeseed:Raps`,
      description: $localize`:@@crop.rapeseed.desc:Raps`,
      image: 'raps.webp',
      pest: 'Rapsglanzkäfer',
      yields: { veryHigh: '≥ 44', high: '34-43', moderate: '24-33', low: '14-23', veryLow: '< 14' },
      baseYield: 40,
      soilSensitivity: 1.2,
      nutritionSensitivity: 1.3,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 150, organic: 180 },
      marketValue: { conventional: 45, organic: 65 },
    },
    Pea: {
      id: 'Pea',
      name: $localize`:@@crop.pea:Erbse`,
      description: $localize`:@@crop.pea.desc:Erbse`,
      image: 'erbse.webp',
      pest: 'Erbsenwickler',
      yields: { veryHigh: '≥ 40', high: '30-39', moderate: '20-29', low: '10-19', veryLow: '< 10' },
      baseYield: 35,
      soilSensitivity: 1.0,
      nutritionSensitivity: 0.6,
      weatherSensitivity: { drought: 'Stark', cold: 'Mäßig', flood: 'Stark' },
      seedPrice: { conventional: 100, organic: 125 },
      marketValue: { conventional: 25, organic: 45 },
      special: 'Erbsen erhöhen den Mineralstoffgehalt und die Bodenqualität.',
    },
  } as Record<string, CropConfig>,
  EXPENSES: {
    RUNNING: {
      ORGANIC_CONTROL: 500,
      FERTILIZE: 100,
      PESTICIDE: 100,
      ORGANISMS: 150,
      ANIMALS: 250,
      BASE_CONVENTIONAL: 1000,
      BASE_ORGANIC: 1500,
    },
  },
  ROTATION_MATRIX: {
    Fieldbean: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'bad',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'ok',
      Pea: 'bad',
    },
    Barley: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'bad',
      Oat: 'bad',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'ok',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Oat: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'good',
      Oat: 'bad',
      Potato: 'ok',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'ok',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Potato: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'ok',
      Oat: 'ok',
      Potato: 'bad',
      Corn: 'ok',
      Rye: 'ok',
      Wheat: 'ok',
      Beet: 'ok',
      Rapeseed: 'ok',
      Pea: 'good',
    },
    Corn: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'bad',
      Oat: 'ok',
      Potato: 'good',
      Corn: 'bad',
      Rye: 'bad',
      Wheat: 'bad',
      Beet: 'good',
      Rapeseed: 'ok',
      Pea: 'good',
    },
    Rye: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'ok',
      Rye: 'bad',
      Wheat: 'ok',
      Beet: 'ok',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Wheat: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'bad',
      Oat: 'ok',
      Potato: 'good',
      Corn: 'good',
      Rye: 'bad',
      Wheat: 'bad',
      Beet: 'good',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Beet: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'ok',
      Oat: 'ok',
      Potato: 'good',
      Corn: 'ok',
      Rye: 'ok',
      Wheat: 'ok',
      Beet: 'bad',
      Rapeseed: 'ok',
      Pea: 'good',
    },
    Rapeseed: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'ok',
      Barley: 'good',
      Oat: 'good',
      Potato: 'ok',
      Corn: 'ok',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'ok',
      Rapeseed: 'bad',
      Pea: 'ok',
    },
    Pea: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'bad',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'ok',
      Pea: 'bad',
    },
    Fallow: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'ok',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Grass: {
      Grass: 'bad',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'good',
      Pea: 'good',
    },
  } as Record<CropType, Record<CropType, 'good' | 'ok' | 'bad'>>,
};
