import type { CropType } from './types';

interface CropConfig {
  id: CropType;
  name: string;
  description: string;
  image: string;
  pest: string;
  yields: {
    veryHigh: string;
    high: string;
    moderate: string;
    low: string;
    veryLow: string;
  };
  baseYield: number;
  soilSensitivity: number;
  nutritionSensitivity: number;
  weatherSensitivity: {
    drought: string;
    cold: string;
    flood: string;
  };
  seedPrice: {
    conventional: number;
    organic: number;
  };
  marketValue: {
    conventional: number;
    organic: number;
  };
  laborHours: number;
  special?: string;
}

export const APP_DOMAIN = 'https://soil.app';

export const GEMINI_MODEL = 'gemini-3-flash-preview';

export const GAME_CONSTANTS = {
  DEFAULT_ROUNDS: 20,
  SOIL: {
    START: 100,
    FALLOW_RECOVERY: 2.0,
    CROP_ROTATION_BONUS: 0.5,
    CROP_ROTATION_PENALTY: -0.5,
    FERTILIZER_SYNTHETIC_IMPACT: -0.1,
    PESTICIDE_IMPACT: -0.1,
    MACHINE_IMPACT: [0, -0.2, -0.5, -1.5, -5.0],
    ORGANISMS_SOIL_BONUS: 0.1,
    MONOCULTURE_PENALTY: -0.5,
    NUTRITION_OVER_PENALTY_START: 130,
    NUTRITION_OVER_PENALTY_FACTOR: -0.05,
    SYNTHETIC_BURN_THRESHOLD: 150,
    SYNTHETIC_BURN_PENALTY: -2.0,
    PLANTATION_GAINS: {
      Fieldbean: 2.0,
      Pea: 1.5,
      Oat: 0.5,
      Rye: 0.5,
      Beet: 0.2,
      Grass: 2.0,
    } as Record<string, number>,
    PLANTATION_LOSSES: {
      Barley: -0.2,
      Potato: -1.0,
      Corn: -1.0,
      Wheat: -0.2,
      Beet: -0.2,
      Rapeseed: -0.2,
    } as Record<string, number>,
  },
  NUTRITION: {
    START: 100,
    MAX: 150,
    BASE_DECLINE: 0.15,
    FERTILIZER_SYNTHETIC: 50,
    FERTILIZER_ORGANIC: 25,
    FIELDBEAN_BONUS: 15,
    ANIMALS_REQUIRED_RATIO: 0.2,
  },
  MACHINE_FACTORS: {
    // References for Labor & Machinery:
    // https://www.ktbl.de/webanwendungen/standarddeckungsbeitraege (KTBL Datensammlungen)
    YIELD_BONUS: [0, 0.1, 0.2, 0.3, 0.4],
    LABOR_COST_PER_HOUR: 25, // Average cost per hour for labor
    PERSONNEL_COST: 12000, // Increased base overhead/management cost per year
    INVESTMENT_COST: [0, 2000, 8000, 20000, 50000],
    MAINTENANCE_COST: [0, 500, 2000, 6000, 15000],
  },
  WEATHER_EFFECTS: {
    // References for Weather Impacts:
    // https://www.julius-kuehn.de/pb/klimaanpassung (JKI Klimafolgen)
    // https://www.bmel-statistik.de/landwirtschaft/ernte-und-qualitaet/getreideernte/ergebnisse
    Normal: { yield: 1.0, soil: 0, name: 'Normal' },
    Drought: { yield: 0.55, soil: -1.2, name: 'Trockenheit' },
    LateFrost: { yield: 0.7, soil: 0, name: 'Spätfrost' },
    HeatWave: { yield: 0.65, soil: -2.0, name: 'Hitzewelle' },
    Flood: { yield: 0.5, soil: -3.0, name: 'Starkregen/Hochwasser' },
    Storm: { yield: 0.75, soil: -1.0, name: 'Sturm' },
  } as Record<string, { yield: number; soil: number; name: string }>,
  VERMIN_EFFECTS: {
    // References for Pests:
    // https://www.isip.de/ (Informationssystem Integrierte Pflanzenproduktion)
    // https://www.pflanzenkrankheiten.ch/
    // https://www.fli.de/de/aktuelles/tierseuchengeschehen/afrikanische-schweinepest/ (ASP Info)
    'aphid-black': { name: 'Schwarze Bohnenlaus' },
    'aphid-cereal': { name: 'Getreideblattlaus' },
    'potato-beetle': { name: 'Kartoffelkäfer' },
    'corn-borer': { name: 'Maiszünsler' },
    'pollen-beetle': { name: 'Rapsglanzkäfer' },
    'pea-moth': { name: 'Erbsenwickler' },
    nematode: { name: 'Rübennematode' },
    'oat-rust': { name: 'Haferkronenrost' },
    'swine-fever': { name: 'Afrikanische Schweinepest' }, // Affects Animals (Pigs)
  } as Record<string, { name: string }>,
  CROPS: {
    // Yields & Prices based on 2024/2025 Data:
    // https://www.bmel-statistik.de/landwirtschaft/ernte-und-qualitaet/getreideernte/ergebnisse
    // https://www.bmel-statistik.de/landwirtschaft/ernte-und-qualitaet/kartoffelernte
    Fieldbean: {
      id: 'Fieldbean',
      name: 'Ackerbohne',
      description: 'Ackerbohne',
      image: 'ackerbohne.webp',
      pest: 'Schwarze Bohnenlaus',
      yields: { veryHigh: '≥ 44', high: '32-43', moderate: '21-31', low: '11-20', veryLow: '< 11' },
      baseYield: 60,
      soilSensitivity: 1.0,
      nutritionSensitivity: 0.5,
      weatherSensitivity: { drought: 'Stark', cold: 'Mäßig', flood: 'Stark' },
      seedPrice: { conventional: 150, organic: 180 },
      marketValue: { conventional: 25, organic: 45 },
      laborHours: 12,
      special: 'Ackerbohnen erhöhen den Mineralstoffgehalt und die Bodenqualität.',
    },
    Barley: {
      id: 'Barley',
      name: 'Gerste',
      description: 'Gerste',
      image: 'gerste.webp',
      baseYield: 110,
      soilSensitivity: 1.2,
      nutritionSensitivity: 0.8,
      pest: 'Getreideblattlaus',
      yields: { veryHigh: '≥ 82', high: '59-81', moderate: '39-58', low: '20-38', veryLow: '< 20' },
      weatherSensitivity: { drought: 'Mäßig', cold: 'Mäßig', flood: 'Mäßig' },
      seedPrice: { conventional: 90, organic: 110 },
      marketValue: { conventional: 24, organic: 38 },
      laborHours: 8,
      special: 'Gerste ist robust und vielseitig.',
    },
    Oat: {
      id: 'Oat',
      name: 'Hafer',
      description: 'Hafer',
      image: 'hafer.webp',
      pest: 'Haferkronenrost',
      yields: { veryHigh: '≥ 63', high: '45-62', moderate: '30-44', low: '15-29', veryLow: '< 15' },
      baseYield: 100,
      soilSensitivity: 1.1,
      nutritionSensitivity: 0.7,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 80, organic: 100 },
      marketValue: { conventional: 26, organic: 45 },
      laborHours: 8,
      special: 'Hafer verbessert die Bodenqualität.',
    },
    Potato: {
      id: 'Potato',
      name: 'Kartoffel',
      description: 'Kartoffel',
      image: 'kartoffel.webp',
      pest: 'Kartoffelkäfer',
      yields: { veryHigh: '≥ 560', high: '405-559', moderate: '270-404', low: '135-269', veryLow: '< 135' },
      baseYield: 450,
      soilSensitivity: 1.2,
      nutritionSensitivity: 1.0,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 2500, organic: 3000 },
      marketValue: { conventional: 15, organic: 32 },
      laborHours: 100,
    },
    Corn: {
      id: 'Corn',
      name: 'Mais',
      description: 'Mais',
      image: 'mais.webp',
      pest: 'Maiszünsler',
      yields: { veryHigh: '≥ 125', high: '90-124', moderate: '60-89', low: '30-59', veryLow: '< 30' },
      baseYield: 110,
      soilSensitivity: 1.4,
      nutritionSensitivity: 1.0,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 100, organic: 120 },
      marketValue: { conventional: 35, organic: 50 },
      laborHours: 30,
    },
    Rye: {
      id: 'Rye',
      name: 'Roggen',
      description: 'Roggen',
      image: 'roggen.webp',
      pest: 'Getreideblattlaus',
      yields: { veryHigh: '≥ 75', high: '54-74', moderate: '36-53', low: '18-35', veryLow: '< 18' },
      baseYield: 100,
      soilSensitivity: 1.0,
      nutritionSensitivity: 0.7,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Mäßig', flood: 'Stark' },
      seedPrice: { conventional: 90, organic: 110 },
      marketValue: { conventional: 25, organic: 40 },
      laborHours: 10,
      special: 'Roggen verbessert die Bodenqualität.',
    },
    Wheat: {
      id: 'Wheat',
      name: 'Weizen',
      description: 'Weizen',
      image: 'weizen.webp',
      pest: 'Getreideblattlaus',
      yields: { veryHigh: '≥ 94', high: '68-93', moderate: '45-67', low: '23-44', veryLow: '< 23' },
      baseYield: 110,
      soilSensitivity: 1.4,
      nutritionSensitivity: 1.1,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 100, organic: 120 },
      marketValue: { conventional: 30, organic: 45 },
      laborHours: 10,
    },
    Beet: {
      id: 'Beet',
      name: 'Zuckerrübe',
      description: 'Zuckerrübe',
      image: 'zuckerruebe.webp',
      pest: 'Rübennematode',
      yields: { veryHigh: '≥ 1060', high: '765-1059', moderate: '510-764', low: '255-509', veryLow: '< 255' },
      baseYield: 750,
      soilSensitivity: 1.1,
      nutritionSensitivity: 1.0,
      weatherSensitivity: { drought: 'Stark', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 1200, organic: 1500 },
      marketValue: { conventional: 6.5, organic: 9.5 },
      laborHours: 60,
      special: 'Zuckerrüben verbessern die Bodenqualität.',
    },
    Rapeseed: {
      id: 'Rapeseed',
      name: 'Raps',
      description: 'Raps',
      image: 'raps.webp',
      pest: 'Rapsglanzkäfer',
      yields: { veryHigh: '≥ 44', high: '32-43', moderate: '21-31', low: '11-20', veryLow: '< 11' },
      baseYield: 60,
      soilSensitivity: 1.0,
      nutritionSensitivity: 1.3,
      weatherSensitivity: { drought: 'Mäßig', cold: 'Stark', flood: 'Stark' },
      seedPrice: { conventional: 150, organic: 180 },
      marketValue: { conventional: 44, organic: 65 },
      laborHours: 12,
    },
    Pea: {
      id: 'Pea',
      name: 'Erbse',
      description: 'Erbse',
      image: 'erbse.webp',
      pest: 'Erbsenwickler',
      yields: { veryHigh: '≥ 38', high: '27-37', moderate: '18-26', low: '9-17', veryLow: '< 9' },
      baseYield: 50,
      soilSensitivity: 0.9,
      nutritionSensitivity: 0.6,
      weatherSensitivity: { drought: 'Stark', cold: 'Mäßig', flood: 'Stark' },
      seedPrice: { conventional: 100, organic: 125 },
      marketValue: { conventional: 28, organic: 48 },
      laborHours: 12,
      special: 'Erbsen erhöhen den Mineralstoffgehalt und die Bodenqualität.',
    },
    Grass: {
      id: 'Grass',
      name: 'Tiere',
      description: 'Wiese für Tierhaltung',
      image: 'hausschwein.webp',
      pest: 'Afrikanische Schweinepest',
      yields: { veryHigh: '≥ 94', high: '68-93', moderate: '45-67', low: '23-44', veryLow: '< 23' },
      baseYield: 100,
      soilSensitivity: 0.5,
      nutritionSensitivity: 0.5,
      weatherSensitivity: { drought: 'Gering', cold: 'Gering', flood: 'Mäßig' },
      seedPrice: { conventional: 100, organic: 120 },
      marketValue: { conventional: 12, organic: 20 },
      laborHours: 15,
    },
  } as Record<string, CropConfig>,
  EXPENSES: {
    RUNNING: {
      ORGANIC_CONTROL: 1500, // Annual control fee
      FERTILIZE: 400,
      PESTICIDE: 500,
      ORGANISMS: 600,
      ANIMALS: 500,
    },
  },
  ROTATION_MATRIX: {
    Fieldbean: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'bad',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'ok',
      Pea: 'bad',
    },
    Barley: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'bad',
      Oat: 'bad',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'ok',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Oat: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'good',
      Oat: 'bad',
      Potato: 'ok',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'ok',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Potato: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'ok',
      Oat: 'ok',
      Potato: 'bad',
      Corn: 'ok',
      Rye: 'ok',
      Wheat: 'ok',
      Beet: 'ok',
      Rapeseed: 'ok',
      Pea: 'good',
    },
    Corn: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'bad',
      Oat: 'ok',
      Potato: 'good',
      Corn: 'bad',
      Rye: 'bad',
      Wheat: 'bad',
      Beet: 'good',
      Rapeseed: 'ok',
      Pea: 'good',
    },
    Rye: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'ok',
      Rye: 'bad',
      Wheat: 'ok',
      Beet: 'ok',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Wheat: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'bad',
      Oat: 'ok',
      Potato: 'good',
      Corn: 'good',
      Rye: 'bad',
      Wheat: 'bad',
      Beet: 'good',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Beet: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'ok',
      Oat: 'ok',
      Potato: 'good',
      Corn: 'ok',
      Rye: 'ok',
      Wheat: 'ok',
      Beet: 'bad',
      Rapeseed: 'ok',
      Pea: 'good',
    },
    Rapeseed: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'ok',
      Barley: 'good',
      Oat: 'good',
      Potato: 'ok',
      Corn: 'ok',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'ok',
      Rapeseed: 'bad',
      Pea: 'ok',
    },
    Pea: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'bad',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'ok',
      Pea: 'bad',
    },
    Fallow: {
      Grass: 'good',
      Fallow: 'good',
      Fieldbean: 'ok',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'good',
      Pea: 'good',
    },
    Grass: {
      Grass: 'bad',
      Fallow: 'good',
      Fieldbean: 'good',
      Barley: 'good',
      Oat: 'good',
      Potato: 'good',
      Corn: 'good',
      Rye: 'good',
      Wheat: 'good',
      Beet: 'good',
      Rapeseed: 'good',
      Pea: 'good',
    },
  } as Record<CropType, Record<CropType, 'good' | 'ok' | 'bad'>>,
};
