# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b6253ddbaaabb01b6333a1b5d4f1c0c233b2d6bff0d4a72cf2e40db33a36f65a01a2e348282920ad17197d9cd559fdcc85696d3708ef80313037f3d3825a269

test:
  secret_key_base: d8cee34afe32f162c60c1dd923859eaadd8941ee51e7f1836a969393b82e472f31a24cc78bd77317493da60ca89f49635b215fa122be999dd443f082ab7361a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
