import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Background Sync for Firebase Functions (Drafts, Submissions)
const bgSyncPlugin = new BackgroundSyncPlugin('game-sync-queue', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours
  onSync: async ({ queue }) => {
    // Notify clients that sync started
    const clients = await self.clients.matchAll();
    for (const client of clients) {
      client.postMessage({ type: 'SYNC_STARTED' });
    }

    try {
      await queue.replayRequests();
      // Notify clients that sync completed
      for (const client of clients) {
        client.postMessage({ type: 'SYNC_COMPLETED' });
      }
    } catch (error) {
      console.error('Background sync failed:', error);
    }
  },
});

registerRoute(
  ({ url }) => url.origin.includes('cloudfunctions.net'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST',
);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts',
  }),
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  }),
);

// Fallback to index.html for navigation requests (SPA)
registerRoute(
  ({ request }) => request.mode === 'navigate',
  async () => {
    return (await caches.match('/index.html')) || fetch('/index.html');
  },
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
